spring:
  application:
    name: Blood-sample-management-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/spring_bsm_db?createDatabaseIfNOTEXIST=true
    username: root
    password: Root@123

  jpa:
    hibernate:
      ddl-auto : update
      show-sql: true
    properties:
      hibernate:
        forma_sql: true

Server:
  port: 8082

